export const MUSIC_LIST=[
	{	
		id:1,
		title:'十年',
		artist:'杨宗纬',
		file:'../music/杨宗纬-十年.mp3',
		cover:'../music/杨宗纬-十年.mp3'
	},
	{	
		id:2,
		title:'另一个天堂',
		artist:'王力宏&张靓颖',
		file:'../music/王力宏&张靓颖-另一个天堂.mp3',
		cover:'../music/王力宏&张靓颖-另一个天堂.mp3'
	},
	{	
		id:3,
		title:'如果有如果',
		artist:'钱钱',
		file:'../music/浅浅[主播]-如果有如果《十年》(请给我一首歌的时间Vol.647).mp3',
		cover:'../music/浅浅[主播]-如果有如果《十年》(请给我一首歌的时间Vol.647).mp3'
	},
	{	
		id:4,
		title:'烟火的光芒',
		artist:'马天宇',
		file:'../music/马天宇-烟火的光芒.mp3',
		cover:'../music/马天宇-烟火的光芒.mp3'
	},
	{	
		id:5,
		title:'小酒窝',
		artist:'林俊杰&蔡卓妍',
		file:'../music/林俊杰&蔡卓妍-小酒窝.mp3',
		cover:'../music/林俊杰&蔡卓妍-小酒窝.mp3'
	},
	{	
		id:6,
		title:'简单爱',
		artist:'陈奕迅&周杰伦',
		file:'../music/陈奕迅&周杰伦-简单爱.mp3',
		cover:'../music/陈奕迅&周杰伦-简单爱.mp3'
	}
]
